#server
server:
  port: 8890
spring:
  application:
    name: exampl_blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cluster:
      max-redirects:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB # 单个文件的最大值
      max-request-size: 20MB # 上传文件总的最大值

#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.blog.chat.pojo






